### PR TITLE
Tutorial update

### PR DESCRIPTION
**Pull request by millsjdm**
updated group.pdf tutorial

### CODE REVIEW

**Comment by dbinetti** [comment]
Great job!  This is how to put together a PR.  

However, I needed to update the tutorial to reflect the UI changes.  So, look at the most current PDF and edit that one with these changes.  Then resubmit.  (You can use the same PR.  Just overwrite your existing file.).

**Comment by millsjdm** [comment]
Got it.

David Mills - (813) 786-4381
[sent from my Galaxy Note5]

**Comment by millsjdm** [comment]
unable to access staging.barberscore.com   (I don't want to use the
production site to create new screen shots).

*J. David Mills*
BHS C&J Committee Chairman
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*

**Comment by dbinetti** [comment]
Are you ready?  I can merge this unless we're waiting on something else.

**Comment by millsjdm** [comment]
not yet - I haven't updated the group.pdf yet


*J. David Mills*
BHS C&J Committee Chairman
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*

**Comment by dbinetti** [comment]
Merging changes. 

Congratulations!  You're an official contributor to the project.  :-)

**Pull request merged**
